import DocsImage from '../../../components/docs/Image';
import errorHandler from '../../../../public/images/docs/global_error_handler.PNG';

# ⛔ 이슈 3: 돌발적인 데이터베이스 접근 실패

### 📝 상황 설명
- 클라이언트에서 로그인 요청을 보냈을 때 백엔드에서 상태 코드가 반환되지 않고, 비정상적으로 서버가 종료됨.
- 백엔드 서버 로그:
  - `/auth/login`의 POST 요청 후, **<u>상태 코드나 에러 메시지 없이</u>** 앱 충돌 발생.
  - Nodemon 로그: `app crashed - waiting for file changes before starting...` (단순히 크래시가 발생했다고만 표기됨)
- 이 문제는 **정상작동 테스트 확인 후** 컴퓨터를 종료하고, 외출을 하고 돌아와서 발생했다.
- 주어진 힌트가 너무나도 부족한 상황.

---

### 🔍 원인 분석

1. **중단점 찾기**

```js filename="authController.js" {4, 6, 9, 11} copy
    const loginController = async (req, res) => {
      try {
        const { id, password } = req.body;
        console.log('테스트1');
        const { user, tokens } = await authService.loginUser(id, password);
        console.log('테스트2');
        setCookie(res, 'accessToken', tokens.accessToken, { maxAge: accessTokenMaxAge });
        setCookie(res, 'refreshToken', tokens.refreshToken, { maxAge: refreshTokenMaxAge });
        console.log('테스트3');
        res.status(200).json({ user });
        console.log('테스트4');
      } catch (error) {
        const { statusCode, message }
           = createErrorResponse(error.status || 500, error.message || "로그인 중 오류가 발생했습니다.");
        res.status(statusCode).json({ message });
      }
    };
```

 - 힌트가 너무 없기 때문에 **로직이 어디서 멈췄는지** 부터 확인해야 한다. 따라서 `loginController`에 더미 로그를 추가
 - 결과: `테스트1`까지만 출력됨. `authService.loginUser`에서 실행이 중단된 것으로 보임.

2. **의심 영역 좁히기**
 - **서비스 로직 점검**
- `authService.loginUser`는 MongoDB와 상호작용하는 코드임을 확인. [authService](https://github.com/LeeHyunWoo2/KIN-Web/blob/91d4f3990e491488c4032d4aa65e016fcc7aadb1/backend/services/user/authService.js#L44)
- **정상 작동 코드 그대로 구동했다는 가정 하에** 해당 함수에서 문제가 발생할 가능성이 있는 원인은 <u>단순한 연결 실패</u> 정도로 추측됨.
- 일반적으로 예상되는 연결 실패 시나리오는 이 정도로 예상된다.
  1. 개발환경의 인터넷 연결이 끊김
  2. DB가 셧다운됨
  3. DB 로그인에 실패함
  4. 로컬 환경의 IP가 차단됨

 - **데이터베이스 연결 상태 점검**
- ✔️ 개발 환경의 인터넷은 정상적으로 연결되어 있음을 확인 -> 1번 제외
- ✔️ 배포중인 서버에서 테스트해본 결과 정상 작동을 확인. 따라서 개발 환경의 **접근 권한 문제**로 추리영역을 좁혀나감 -> 2번 제외
- ✔️ 배포와 로컬 두 환경이 **동일한 환경변수를 통해** 접속하고 있음. -> 3번 제외
- ❌ 남은 후보는 4번. **IP차단**의 가능성이 매우 높아짐.
- 💡 또한 증상이 **자리를 비운 이후에** 컴퓨터 부팅을 해보니 발생했다는 부분도 중요 단서.

3. **원인 확인**
- 보안을 위해 클라우드 MongoDB 특정 IP만 접근을 허용하는 **화이트리스트**를 설정해 놓았음.
- 개발 환경 즉, 집의 인터넷은 통신사 공인 유동 IP를 사용중임
- 외출 후 컴퓨터를 부팅하고 확인해보니 안된다? -> 외출하고 온 사이에 집 인터넷 공인 IP가 변경되어 화이트리스트에서 제외된것.
- 로컬 환경에서 MongoDB에 연결을 시도했으나, IP 차단으로 인해 연결 실패 → 서비스 로직이 중단됨.

---

### 🛠️ 해결 방안:

1. **클라우드 MongoDB 화이트리스트 갱신**
- 새로 변경된 IP를 MongoDB 클라우드 대시보드의 화이트리스트에 추가. 이것만으로 문제 자체는 해결된다.
- 이 문제는 어렵지 않게 원인을 찾고, 해결 방안도 간단했지만, 문제가 발생했을 때 **너무나도 단서가 없었다는 점**에서 로깅에 개선이 필요함을 느꼈다.

2. **전역 uncaught 에러 핸들러 추가**
```js filename="server.js" copy
process.on('uncaughtException', (err) => {
    console.error('[에러] Uncaught Exception:', err);
});

process.on('unhandledRejection', (reason, promise) => {
    console.error('[에러] Unhandled Rejection:', reason);
});
   ```

- 이 핸들러를 통해 로직 내에서 미처 탐지하지 못한 Exception, promise reject가 발생해도 확인이 가능하다.

3. **로깅 라이브러리 및 필터 추가**
```js filename="logger.js" copy
// 커스텀 토큰 생성: query, errorMessage
morgan.token('query', (req) => JSON.stringify(req.query || {}));
morgan.token('errorMessage', (req, res) => {
    return res.statusCode >= 400 ? `Error: ${res.statusMessage || 'Unknown error'}` : '';
});

// 로그 포맷 정의
const logFormat = ':time / :method :url [:status] query: :query body: :body :errorMessage';
   ```
- Morgan 로깅 미들웨어를 도입, 설정 파일 작성.
- [코드 링크](https://github.com/LeeHyunWoo2/KIN-Web/blob/91d4f3990e491488c4032d4aa65e016fcc7aadb1/backend/middleware/logger.js#L37)

<br/>

  ---

  ### ✅ 결과

  - 화이트리스트 갱신 후 테스트 결과, 로그인 요청이 정상적으로 처리되고 서버도 안정적으로 동작함.

<br/>

<DocsImage src={errorHandler} alt="logs"/>

  - (동일한 에러를 발생시켜본 결과, **IP that isn't whitelisted** 라고 명시되는것을 확인할 수 있다.)
  - 또한 Morgan 을 통해 기본적인 요청의 흐름을 파악할 수 있게 되었다.


### 💡 배운 점
  - 내가 무엇을, 어떤 환경에서 개발하는것인지 명확하게 이해하고 있었기 때문에 큰 고생을 하지 않았고, 자신감과 확신을 얻는 좋은 경험이 되었습니다.
  - 로깅의 중요성. 데이터와 로직의 흐름을 확인할 수 있어야 빠르고 정확하게 대응이 가능하다는점을 배웠습니다.

<br/>
> 겉으로는 단순하고 예사롭게 보일 수 있는 사례일지라도,<br/>
> 데이터베이스 접속 문제 상황에서 곧바로 인터넷의 공인 IP 변경 가능성을 추론하는 신입 개발자는 흔치 않을 것입니다.<br/>
> 이는 저의 문제 해결 능력과 판단력의 강점을 잘 보여주는 부분이라고 생각합니다.